DROP TABLE IF EXISTS GROUP;


CREATE TABLE GROUP ( 
GROUP_ID INT  NOT NULL PRIMARY KEY,
 ITEM_ID VARCHAR(8) NOT NULL);

 

DROP TABLE IF EXISTS STAFF;


CREATE TABLE STAFF( 
ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY , 
STAFF_ID VARCHAR(8) NOT NULL, 
ITEM_ID INT NOT NULL FOREIGN KEY , 
ITEM_DESCRIPTION  VARCHAR(30)) ;


DROP TABLE IF EXISTS SUBORDER;
 

CREATE TABLE SUBORDER( 
SUBORDER_ID INT NOT NULL PRIMARY KEY, 
ORDER_NUMBER INT NOT NULL , 
ORDER_DESCRIPTION VARCHAR(30) NOT NULL , 
QUANTITY INT NOT NULL , 
ITEM_ID INT NOT NULL , 
TOP1 VARCHAR(30) , 
TOP2 VARCHAR(30) ,
 TOP3 VARCHAR(30), 
 PRICE INT NOT NULL, 
 ORDER_STATUS VARCHAR(30), 
 GROUP_ID INT NOT NULL FOREIGN KEY)
 

DROP TABLE IF EXISTS ITEM;


CREATE TABLE ITEM (


ITEM_ID INT NOT NULL PRIMARY KEY,
ITEM_NAME VARCHAR(30) ,
PRICE INT NOT NULL);